use std::fs::File;
use std::io::Write;
use std::path::PathBuf;
use crate::qc::QCMetrics;
use crate::biomarkers::get_cancer_panels;

pub fn generate_clinical_report(
    output_path: &PathBuf,
    qc: &QCMetrics,
    abundances: &std::collections::HashMap<String, f64>,
    panels: &[&str],
) -> Result<(), Box<dyn std::error::Error>> {
    let mut file = File::create(output_path)?;

    // HTML header
    writeln!(file, "<!DOCTYPE html>")?;
    writeln!(file, "<html>")?;
    writeln!(file, "<head>")?;
    writeln!(file, "  <title>RNA-Pop Clinical Report</title>")?;
    writeln!(file, "  <style>")?;
    writeln!(file, "    body {{ font-family: Arial, sans-serif; margin: 20px; }}")?;
    writeln!(file, "    h1 {{ color: #2c3e50; }}")?;
    writeln!(file, "    h2 {{ color: #34495e; border-bottom: 2px solid #3498db; }}")?;
    writeln!(file, "    table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}")?;
    writeln!(file, "    th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}")?;
    writeln!(file, "    th {{ background-color: #3498db; color: white; }}")?;
    writeln!(file, "    .up {{ color: #e74c3c; font-weight: bold; }}")?;
    writeln!(file, "    .down {{ color: #27ae60; font-weight: bold; }}")?;
    writeln!(file, "    .warning {{ background-color: #f39c12; color: white; padding: 2px 6px; border-radius: 3px; }}")?;
    writeln!(file, "    .pass {{ background-color: #27ae60; color: white; padding: 2px 6px; border-radius: 3px; }}")?;
    writeln!(file, "  </style>")?;
    writeln!(file, "</head>")?;
    writeln!(file, "<body>")?;

    // Title
    writeln!(file, "<h1>RNA-Pop Clinical Report</h1>")?;
    writeln!(file, "<p>Generated by RNA-Pop v0.1.0</p>")?;

    // QC Section
    writeln!(file, "<h2>Quality Control</h2>")?;
    writeln!(file, "<table>")?;
    writeln!(file, "  <tr><th>Metric</th><th>Value</th><th>Status</th></tr>")?;
    writeln!(file, "  <tr><td>Total reads</td><td>{}</td><td><span class='pass'>PASS</span></td></tr>", qc.total_reads)?;
    writeln!(file, "  <tr><td>Mapping rate</td><td>{:.1}%</td><td><span class='{}'>{}</span></td></tr>",
        qc.mapping_rate,
        if qc.mapping_rate > 90.0 { "pass" } else { "warning" },
        if qc.mapping_rate > 90.0 { "PASS" } else { "WARN" }
    )?;
    writeln!(file, "  <tr><td>Unique mapped</td><td>{}</td><td><span class='pass'>PASS</span></td></tr>", qc.unique_mapped)?;
    writeln!(file, "  <tr><td>Avg mapping quality</td><td>{:.1}</td><td><span class='{}'>{}</span></td></tr>",
        qc.avg_mapping_quality,
        if qc.avg_mapping_quality > 30.0 { "pass" } else { "warning" },
        if qc.avg_mapping_quality > 30.0 { "PASS" } else { "WARN" }
    )?;
    writeln!(file, "  <tr><td>Transcripts covered</td><td>{}/{} ({:.1}%)</td><td><span class='pass'>PASS</span></td></tr>",
        qc.transcripts_with_coverage, qc.total_transcripts,
        qc.transcripts_with_coverage as f64 / qc.total_transcripts as f64 * 100.0
    )?;
    writeln!(file, "</table>")?;

    // Biomarker panels
    for panel_name in panels {
        writeln!(file, "<h2>Cancer Biomarker Panel: {}</h2>", panel_name.to_uppercase())?;
        writeln!(file, "<table>")?;
        writeln!(file, "  <tr><th>Gene</th><th>Expression</th><th>Expected in Cancer</th><th>Clinical Significance</th></tr>")?;

        let panels = get_cancer_panels();
        if let Some(biomarkers) = panels.get(*panel_name) {
            for bm in biomarkers {
                if let Some(&abundance) = abundances.get(&bm.rna_name) {
                    let status_class = if bm.direction == "up" { "up" } else { "down" };
                    writeln!(file, "  <tr>")?;
                    writeln!(file, "    <td>{}</td>", bm.gene)?;
                    writeln!(file, "    <td>{:.6}</td>", abundance)?;
                    writeln!(file, "    <td class='{}'>{}</td>", status_class, bm.direction)?;
                    writeln!(file, "    <td>{}</td>", bm.clinical_significance)?;
                    writeln!(file, "  </tr>")?;
                }
            }
        }

        writeln!(file, "</table>")?;
    }

    // Footer
    writeln!(file, "<hr>")?;
    writeln!(file, "<p><small>Report generated by RNA-Pop. For research use only. Not for clinical diagnosis.</small></p>")?;
    writeln!(file, "</body>")?;
    writeln!(file, "</html>")?;

    Ok(())
}
